language: python
addons:
  chrome: stable
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
cache: pip
install:
  - pip install -r requirements.txt
script:
  - python -m unittest tests/test_back_end.py
  - python -m unittest tests/test_front_end.py